name: Deploy

on:
  push:
    branches: ["main"]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Create SSH key 
        run: |
          echo "${{ secrets.KEY }}" > /tmp/key.pem
          chmod 600 /tmp/key.pem

      - name: Clean old 
        run: |
          ssh -o StrictHostKeyChecking=no -i /tmp/key.pem ubuntu@${{ secrets.HOST }} << 'EOF'
            rm -rf /home/ubuntu/app
            mkdir -p /home/ubuntu/app
          EOF

      - name: Copy code
        run: |
          scp -o StrictHostKeyChecking=no -i /tmp/key.pem -r * .[^.]* ubuntu@${{ secrets.HOST }}:/home/ubuntu/app

      - name: Run app 
        run: |
          ssh -o StrictHostKeyChecking=no -i /tmp/key.pem ubuntu@${{ secrets.HOST }} << 'EOF'
            cd /home/ubuntu/app

            pkill node || true
            
            node app.js &
            echo "App start"
          EOF
