name: Clean Copy Code to EC2

on:
  push:
    branches: ["main"]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Create SSH key safely
        run: |
          echo "${{ secrets.KEY }}" > /tmp/key.pem
          chmod 600 /tmp/key.pem

      - name: Clean old folder on EC2
        run: |
          ssh -o StrictHostKeyChecking=no -i /tmp/key.pem ubuntu@${{ secrets.HOST }} << 'EOF'
            rm -rf /home/ubuntu/app
            mkdir -p /home/ubuntu/app
          EOF

      - name: Copy fresh code to EC2
        run: |
          scp -o StrictHostKeyChecking=no -i /tmp/key.pem -r * .[^.]* ubuntu@${{ secrets.HOST }}:/home/ubuntu/app
